<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <AssemblyName>MultliplayerGoesBRRRRRR</AssemblyName>
    <Product>Multliplayer goes BRRRR</Product>
    <GUID>dev.lucas11.mgb</GUID>
    <Version>0.0.1</Version>
    <Nullable>enable</Nullable>
    <LangVersion>13.0</LangVersion>
    <RestoreAdditionalProjectSources>
      https://api.nuget.org/v3/index.json;
      https://nuget.bepinex.dev/v3/index.json;
      https://nuget.samboy.dev/v3/index.json
    </RestoreAdditionalProjectSources>
    <RootNamespace>MultliplayerGoesBRRRRRR</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BepInEx.Analyzers" Version="1.*" PrivateAssets="all" />
    <PackageReference Include="BepInEx.Core" Version="5.*" />
    <PackageReference Include="UltraModding.PluginInfoGenerator" Version="4.*" />
    <PackageReference Include="UnityEngine.Modules" Version="2022.3.28" IncludeAssets="compile" />
  </ItemGroup>
  
  <ItemGroup>
    <Reference Include="Assembly-CSharp">
      <HintPath>C:\Program Files (x86)\Steam\steamapps\common\ULTRAKILL/ULTRAKILL_Data/Managed/Assembly-CSharp.dll</HintPath>
    </Reference>
    <Reference Include="Facepunch.Steamworks.Win64">
      <HintPath>..\..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\ULTRAKILL\ULTRAKILL_Data\Managed\Facepunch.Steamworks.Win64.dll</HintPath>
    </Reference>
  </ItemGroup>
  
</Project>
